LibreCAD/LibreCAD

- libraries/libdxfrw/src/drw_objects.cpp
- libraries/libdxfrw/src/intern/drw_textcodec.cpp
- libraries/libdxfrw/src/libdxfrw.cpp
- librecad/src/lib/engine/rs_system.cpp
- librecad/src/lib/filters/rs_filterdxfrw.cpp
- librecad/src/lib/filters/rs_filterjww.cpp
- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/ui/forms/qg_cadtoolbarmodify.cpp
- (style) Same expression on both sides of '||'
- (performance) Prefer prefix ++/-- operators for non-primitive types
> Fix cppcheck warnings:

- librecad/src/lib/engine/rs_circle.cpp
- librecad/src/lib/engine/rs_circle.h
*Side note*: `RS_Ellipse` handles full ellipses and ellipse arcs, but for circles we have `RS_Circle` for full circles only and `RS_Arc` for circular arcs. Is there any reason to keep these as separate classes? Why not add `angle1` and `angle2` to `RS_Circle` like in `RS_Ellipse`?
> Add full circle area function

- librecad/src/lib/engine/rs.h
- librecad/src/lib/filters/rs_filterdxfrw.cpp
Not completely sure what magnification factor should be used for tiny line patterns in DXF files, but I used 0.15x.
> fixed issue #498: Tiny line styles aren't saved

- librecad/src/ui/qg_actionfactory.cpp
The Statusbar option in the View menu is now checked by default to reflect that the status bar is displayed by default. This should fix issue #500.
> Fixing issue #500. Setting the checkbox for the Statusbar option in the view menu.

- librecad/src/actions/rs_actiondrawellipseaxis.h
Was reading through the rs_actiondrawellipse* files two days back and saw this spelling error in rs_actiondrawellipseaxis.h. I've just fixed it.
> Corrected a comment's spelling in drawwllipseaxis.h

- librecad/src/lib/actions/rs_actioninterface.h
Hi,
I needed this fix in order to compile the project again, otherwise:
```
dinkel@dale:~/Development/LibreCAD (master)$ qmake -r linrecad.pro
[SNIP]
dinkel@dale:~/Development/LibreCAD (master)$ make
[SNIP]
g++ -c -m64 -pipe -g -std=c++11 -O2 -Wall -W -D_REENTRANT -DQC_APPKEY="/LibreCAD" -DQC_APPNAME="LibreCAD" -DQC_COMPANYNAME="LibreCAD" -DQC_COMPANYKEY="LibreCAD" -DQC_VERSION="master" -DQC_DELAYED_SPLASH_SCREEN=1 -DHAS_BOOST=1 -DDWGSUPPORT -DQC_SCMREVISION="2.0.7-162-g0de488c" -DQC_APPDIR="librecad" -DQINITIMAGES_LIBRECAD=qInitImages_librecad -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSvg -I/usr/include/qt4 …
```
> Added (hopefully really needed) include of QObject

- librecad/src/main/qc_applicationwindow.cpp
A wrong icon was used for the 'File -> Export' menu item.
Btw: My editor by default deletes trailing whitespace and so another change in the diff is shown.
> Fixed 'File -> Export' icon

- librecad/src/lib/generators/lc_makercamsvg.cpp
- librecad/src/lib/generators/lc_makercamsvg.h
This extends the MakerCamSVG exporter with spline support. It converts closed and open degree 2  and 3 splines to a series of quadratic resp. cubic bézier curves (the only thing supported by SVG). It is an exact, although not easily reversable, conversion.
Degree 1 splines are not supported because they aren't correctly displayed in LibreCAD anyways (it would just be polylines and not these strange chopped corners and it seems to me, that it would result in some confusion if they don't look the same.
The DXF format would allow to give weights to the different control points (DXF would allow NURBSs), which is not implemented in LibreCAD. This isn't a terribly bad thing for the SVG converter, because one cannot transform NURBS into bézier curves without loss.
It would be cool if at least …
> MakerCamSVG to support splines

- librecad/src/lib/generators/lc_makercamsvg.cpp
After isArc() was renamed to isEllipticArc() in f123224, the generation of ellipses ia SVG elements failed in "Export to MakerCAM SVG".
This is a simple fix, that renames the function call also in lc_makercamsvg.cpp
> Fixed regression of ellipse creation in MakerCamSVG arising from f123224

- libraries/libdxfrw/src/drw_base.h
libdxfrw: Removed unnecessary return statement from "lineWidth2dxfInt(enum lineWidth lw)".
> Minor correction on libdxfrw.

- CLEAN.SH
- common.pri
- scripts/build-dmg-externalqt-clang.sh
- scripts/build-dmg.sh
- scripts/build-osx.sh
Dli,
this are some new build scripts for OSX. 
The goal was to get rid of the modification for settings.pri for the various OSX environments. I also added build-dmg-externalqt-clang.sh for a build with clang and tested with a external version of Qt.
Let me know what you thing.
> Modified build scripts for OSX

- librecad/src/main/helpbrowser.cpp
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/main/qc_applicationwindow.h
- librecad/support/doc/index.html
This launches the default browser and goes to our wiki.
The links under Help → Manual do not work.
> added link to wiki

- librecad/src/cmd/rs_commands.cpp
For "dimension - angular",  "dimension - radial" and "dimension - diametric".
I duplicated dim* commands for "radial" and "diametric", as "radius" and "diameter" may seem more obvious.
> Added new command shortcuts 

- librecad/src/ui/forms/qg_commandwidget.cpp
- librecad/src/ui/forms/qg_commandwidget.h
Implemented bash-behavior for autocompletion : when typing 'sp<tab>', the CL will automatically prompt 'spline' (longest common root for commands starting with 'sp' -> 'spline' & 'spline2').
I would like to pack this piece of code into a function which would return a QString (it would seem more clean). May I use a QG_CommandWidget private method for this ? (e.g. QString autoCompletion(QStringList  const & shortCmdList);).
Rupi
> Extension of command-line autocompletion

- librecad/src/actions/rs_actiondrawcirclecr.cpp
- librecad/src/cmd/rs_commands.cpp
When in mode "circle with center and radius", typing "radius"
in the command-line allow the user to set the radius without moving
hands off the keyboard, but the helper message didn't mentionned that
possibility.
When setting radius from commandline, pressing enter to validate
causes LibreCAD to draw a circle of selected radius at relative zero
position (if no mouse activity into the container) or crosshair
position (if mouse activity into the container).
I added a `switch` test to the `trigger()` method to test the mode, and
if the user is in mode "SetRadius", circle is not drawn & relative zero
is not moved.
`circlecr` and `cc`
> Helper, shortcut & bug correction for "Circle with center & radius" tool

- librecad/src/ui/qg_dialogfactory.cpp
Bug introduced by commit 776c8ae4dbd86ae658202a2174895ce340b0b1dd (`git bisect` information)
Changing from `if(hatch==nullptr)` to `if(hatch)` caused the hatch
dialog box not to show when called.
It seems that this change fixed it... Will see.
Because I reverted a change which happened few times ago, I prefer asking : why was this line changed ? Does it have a goal in particular, that I would have broken by reverting ?
> Fixed bug in hatch dialog box

- librecad/src/lib/gui/rs_graphicview.h
Signals without void type was causing compilation failure.
> Added void-type to signals

- librecad/src/actions/rs_actiondefault.cpp
- librecad/src/lib/gui/rs_graphicview.cpp
- librecad/src/ui/qg_graphicview.cpp
When scrolling with the mouse wheel, you should find:
+ Far less "inch worming" (e.g. mouse top-left, zoom in, mouse bottom-right, zoom out)
+ Zooming out tends to reveal more logical/useful canvas
+ Zooming in tends to center objects that were under the cursor
+ Zooming in on objects near the edge of the view port should now be in a useful position more often
- Seasoned veterans might need to get used to the "drift" or "not working around the old zoom mechanic".
- Not as effective for "just playing with the grid lines" [i.e. zoom_in != inverse(zoom_out)]
Relatedly:
- Zooming is still a bit too choppy, IMO.
- Snapper/Guides are still not redrawn after a zoom event.
> Better zoom-field navigation through basic ZUI "flight" theory

- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/ui/lc_actionfactory.cpp
A tiny change to add a Backspace together with Delete as shortcuts for deleting.
Useful for mac keyboards (like on my linux) without a delete button.
Get the geometry from the activedMdiSubWindow before it is created was generating a coredump
> Added Backspace as shortcut for Delete. 

- .travis.yml
- CI/static-analyzer-reports.sh
this is to enable travis-ci for test building pull requests. In future this can also be used for daily builds.
https://travis-ci.org/LibreCAD/LibreCAD
(doesn't work yet because we don't have this pull request accepted yet)
> travis-ci support

- librecad/src/lib/engine/rs_layerlist.cpp
- librecad/src/lib/engine/rs_layerlist.h
- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/lib/modification/rs_modification.h
fix: blocks moving/pasting bug
Solve the problem with copy-paste or move blocks bug cause some blocks disappears.
Most changes are in ```librecad/src/lib/modification/rs_modification.cpp```.
```RS_Modification::paste``` function has been rewritten.
Closes #715
> Committer: Equoda <Equoda@users.noreply.github.com>

- librecad/src/lib/modification/rs_modification.cpp
Function ```RS_Modification::explode()``` modified. Pen for reparented entities is selected from the original sub-entities now.
> fix:  explode action changes container entities attributes to wrong values; #754

- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/lib/modification/rs_modification.h
Function ```RS_Modification::changeAttributes(...)``` changed.
Overloaded recursive function ```RS_Modification::changeAttributes(...)``` added.
Sub-entities of ```RS_Insert/RS_Block``` now change their attributes together with their containers.
> fix: changing attributes of a block sub-entities; #755

- librecad/src/ui/qg_graphicview.cpp
Trackpads that did not have hi-res scrolling fell back on the
default (mouse) behaviour. This makes behaviour inconsistent between
machines (or even DE's: Gnome X.org has hi-res, Gnome Wayland+XWayland
does not).
This patch assumes that if
`options->device == "Trackpad"`
and
no smooth scrolling
the "scroll wheel" (`QWheelEvent::angleDelta()`) is used instead of
the "trackpad" (`QWheelEvent::pixelDelta()`).
Division by four is an arbitrary constant to make a compromise
between smooth scrolling and scrolling too fast.
This patch makes working with LibreCAD under XWayland the same
experience as under X.org afaik. More work is needed for native
Wayland (`librecad -platform wayland`) support.
Note on the first commit in this PR: it fixes wrong indentation of the altered code. Was too ugly to …
> Fix for Trackpads without smooth/hi-res scrolling

- libraries/jwwlib/src/jwwdoc.cpp
- libraries/libdxfrw/src/drw_header.cpp
- libraries/libdxfrw/src/intern/dwgreader15.cpp
- libraries/libdxfrw/src/intern/dwgreader21.cpp
- librecad/src/lib/engine/lc_splinepoints.cpp
- librecad/src/lib/filters/rs_filterdxfrw.cpp
- librecad/src/ui/forms/qg_arctangentialoptions.cpp
Most of them were misleading indentations, caused by mixed use of tabs
and spaces (or even caused by misleading amount of spaces).
Please have a look over here:
https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/modification/rs_modification.cpp#L538
This thing causes
```
lib/modification/rs_modification.cpp: In member function ‘void RS_Modification::paste(const RS_PasteData&, RS_Graphic*)’:
lib/modification/rs_modification.cpp:539:14: warning: statement has no effect [-Wunused-value]
data.asInsert;
~~~~~^~~~~~~~
```
Afaik, there is no such thing as a `nullptr` exception in C++, but perhaps I am wrong and there exists some compiler that throws them? Either case, having a reference that could be `nullptr`, is _very_ bad design.
I propose on entirely getting rid of that `try` …
> [WIP] Fix all but one compile warning.

- librecad/src/ui/qg_graphicview.cpp
Before this patch, the scroll limits were arbitrary, which
made the user have to use zoom to recenter the scroll perimeter,
in order to navigate the whole document.
This patch limits scrolling to the drawing instead. The exact perimeters
are now so that the drawing is always in the viewport, with an extra
empty zone of 75% for potentially extending the drawing.
This issue got mentioned in #479
> Fix: limit scrolling to drawing + perimeter.

- librecad/src/actions/rs_actionblocksedit.cpp
- librecad/src/lib/engine/rs_hatch.cpp
- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/main/qc_dialogfactory.cpp
Forcing hatch update in '''RS_Hatch::clone()''' to acquire valid '''RS_Hatch*->hatch''' property. Quick fix.
Minor changes in code of '''QC_DialogFactory::requestEditBlockWindow()''', '''RS_Modification::paste()''' and '''RS_ActionBlocksEdit::trigger()'''.
> fix:  Pasted blocks do not contain proper hatch data; #760

- librecad/src/ui/qg_blockwidget.cpp
Force triggering ```slotActivated``` action on right-mouse-button-clicked (context menu) event
> fix: Right mouse button click does not select block in Block List; #759

- librecad/src/lib/engine/rs_layerlist.cpp
- librecad/src/lib/engine/rs_polyline.cpp
- librecad/src/lib/engine/rs_polyline.h
- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/ui/qg_layerwidget.cpp
Wrong logic for layers copying in ```RS_Modification::paste``` corected.
```RS_Polyline::setLayer``` function implemented to change sub-entities layers to the same value.
Some changes in code for better readability and stability
> fix: copied objects are not hidden with other layer objects; #774

- librecad/src/lib/engine/rs_spline.cpp
lib/engine/rs_spline.cpp:592:2: error: 'iota' is not a member of 'std'
include numeric c++ header solves this.
> Fix compile with gcc 5.4

- librecad/src/actions/rs_actioneditundo.cpp
Added trigger ```graphic->setModified(true)``` in ```RS_ActionEditUndo::trigger()``` on "redo" action.
This trigger must be added to any procedure that change draft, because "save/save as" action checks if document is modified.
Changes to be committed:
modified:   librecad/src/actions/rs_actioneditundo.cpp
> fix: Save after Undo does nothing; #803

- librecad/src/lib/math/rs_math.cpp
- librecad/src/lib/math/rs_math.h
This allows for Imperial shorthand translation
prior to the main parser evaluation.
More user-friendly interface at the commandline
as users can use shorthand in relative
or absolute expressions.
examples below.
<pre>
Eval 20'2"+10'11"3/4
Eval (20*12+2)+(10*12+11+3/4)
----------------
Eval 20'2"-10'11"3/4
Eval (20*12+2)-(10*12+11+3/4)
----------------
Eval -10'11"3/4
Eval ()-(10*12+11+3/4)
----------------
Eval 20'2"+10
Eval (20*12+2)+(10)
----------------
</pre>
known issue:
The conditional check of units currently looks at global preferences
unit definition.  It should actually reference the units assigned
to the current drawing.
> Update rs_math.cpp eval fn behavior

- librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
updateAnglePrecision referenced wrong comboBox
> Fix for issue #884 -- Improve Current Drawing Preferences - Units tab

- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
This fix allows for the custom page size values to be entered and stick after clicking 'OK' and returning
to the drawing options page.  It also correctly swaps width and height when toggling from landscape to portrait.  
Selecting 'File | Export | Export as Pdf' will create a document with the correct dimensions.
Selecting 'File | Print' and selecting a tool like pdfcreator does not generate a document.
It has not been tested on a physical printer either.
> fix for Issue #864 -- custom page size - incorrect unit handling

- librecad/src/lib/engine/rs_dimangular.cpp
- librecad/src/lib/math/rs_math.cpp
- librecad/src/lib/math/rs_math.h
Added fmod call in correctAngle to ensure 360 degree results wrap back to 0 degrees.
Added comments to document expected output range of functions.
Added correctAngle2 function with output range of -PI to +PI.
Adjusted Angular dimension code to provide inside/outside angles
rather than inside/supplementary angles. 
Solves issue #824 requested feature of being able to represent outside angles.
> adjusted correctAngle functions to be more consistent. Fix for #824 request.

- librecad/src/ui/qg_dialogfactory.cpp
This allows for any base layer name with a suffix number to be auto
incremented. If no name is supplied it reverts to the default base layer
name of 'noname' and with any additional layers being provided a suffix
number automatically. It is also possible to just use numbered layers
with no base layer name and it will still auto increment correctly...the
only exception being layer '0'. So if you want simple numbered layers
click the + button then replace the default 'noname' layer name in the
dialog with '1' and click 'OK'. From then on highlighting the layer you
want to increment and clicking the '+' button will give you a new layer
with the next available number above the one you just selected.
> fix-new-layer-auto-numbering for issue #935

- libraries/libdxfrw/src/drw_header.cpp
- librecad/src/lib/engine/lc_rect.cpp
- librecad/src/lib/engine/lc_rect.h
- librecad/src/lib/engine/rs_arc.cpp
- librecad/src/lib/engine/rs_color.cpp
- librecad/src/lib/engine/rs_dimension.cpp
- librecad/src/lib/engine/rs_entity.cpp
- librecad/src/lib/engine/rs_entitycontainer.cpp
- librecad/src/lib/engine/rs_leader.cpp
- librecad/src/lib/engine/rs_polyline.cpp
- librecad/src/lib/engine/rs_solid.cpp
- librecad/src/lib/engine/rs_spline.cpp
- librecad/src/lib/engine/rs_spline.h
- librecad/src/lib/engine/rs_undoable.h
- librecad/src/lib/filters/rs_filterdxfrw.h
- librecad/src/lib/gui/rs_dialogfactoryinterface.h
- librecad/src/lib/gui/rs_graphicview.cpp
- librecad/src/lib/math/rs_math.cpp
- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/main/doc_plugin_interface.h
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/plugins/document_interface.h
- librecad/src/ui/forms/qg_exitdialog.cpp
Typos both in source and comments
Found via `codespell -q 3 -I ../librecad-whitelist.txt --skip="*.ts,./libraries"`
> More misc. typos

- .gitignore
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/src.pro
- librecad/src/ui/qg_layerwidget.cpp
- scripts/postprocess-osx.sh
the PlistBuddy line requires the type, misunderstood the issue as it was working sometimes, however the one here works on the command line all the time
The postprocess-osx script was very specific and so now it will use the information gained from qmake to find the lrelease executable, the choice of qmakes to use is able to be done as well so will work for non-path qmake/lrelease.
Added the generated dmg file to .gitignore just in case
sorry about the noise, closed the last pull request and redid it as this as it got ugly
> fix a couple more issues on macOS

- librecad/src/lib/engine/rs_blocklist.h
- librecad/src/lib/engine/rs_entity.h
When compiling the code using VS2017, I get C2600 errors:
error C2600: 'RS_BlockList::RS_BlockList': cannot define a compiler-generated special member function (must be declared in the class first)
error C2600: 'RS_Entity::RS_Entity': cannot define a compiler-generated special member function (must be declared in the class first)
which eventually occur due to ambiguity of the default constructors (what should RS_BlockList() do?)
This change deletes unnecessary definitions and eliminates the error.
> Fix VS error C2600 by removing ambiguity in the default constructor.

- libraries/jwwlib/src/jwwdoc.cpp
When compiling the code using VS2017, I get the following errors:
error C2511: 'void CDataSen::Serialize(std::ofstream &)': overloaded member function not found in 'CDataSen'
error C2511: 'void CDataEnko::Serialize(std::ofstream &)': overloaded member function not found in 'CDataEnko'
error C2511: 'void CDataTen::Serialize(std::ofstream &)': overloaded member function not found in 'CDataTen'
error C2511: 'void CDataMoji::Serialize(std::ofstream &)': overloaded member function not found in 'CDataMoji'
error C2511: 'void CDataSolid::Serialize(std::ofstream &)': overloaded member function not found in 'CDataSolid'
error C2511: 'void CDataBlock::Serialize(std::ofstream &)': overloaded member function not found in 'CDataBlock'
This change corrects function definitions (adds const qualifier), …
> Fix for error C2511: overloaded member function not found in 'CDataSen' etc.

- librecad/src/actions/rs_actiondimangular.cpp
- librecad/src/lib/engine/rs_image.h
- librecad/src/lib/filters/rs_filterdxfrw.h
- librecad/src/lib/gui/rs_graphicview.h
- librecad/src/plugins/document_interface.h
- plugins/importshp/shapelib/ChangeLog
Found via `codespell -q 3 -I ../librecad-whitelist.txt --skip="*.ts,./libraries"`
Whiteslist:
```
amin
ang
ans
behaviour
bload
cancellation
cancelled
ded
ede
emitted
initialisation
lightyear
mesage
ot
que
te
```
> Misc. typos (including doxy)

- librecad/src/lib/engine/rs_dimangular.cpp
dimangular objects should reference getLabel instead of getMeasuredLabel
in order to respect any optionally provided custom label text.
This bug was introduced in #896, and no explanation for the change was given in the commit message, so I assume it was just left over from testing the PR.
> Angular dimensions now respect user's custom label text

- librecad/src/lib/engine/rs_line.cpp
I've noticed the code to draw the line was creating an intersection on a point outside the line and the viewport boundaries and that was resulting in an almost infinite loop when trying to draw the pattern. I just changed the parameter on getIntersection to consider only points on the entities.
> Check viewport intersection only through points along the line

- librecad/src/lib/engine/rs_dimension.cpp
- librecad/src/lib/engine/rs_dimension.h
- librecad/src/lib/engine/rs_line.cpp
- librecad/src/lib/engine/rs_line.h
I split this into two commits because I didn't want a bunch of style fixes to be mixed in with the actual code changes for the reviewer to parse.  Reviewer, it's best to review each commit individually.
The commit message should explain most of the changes:
Improve appearance of inside-horizontal dimensions
* The monolithic method to calculate both inside-horizontal and
aligned dimensions were broken into two separate methods since they
became too different.  As a result, some calculations are duplicated,
so there is still room for improvement.
* Now, dimension text is never offset from the insertion point for
inside-horizontal mode.  This would otherwise be a breaking change,
but inside-horizontal was broken to begin with, so I would rather take
this oppportunity to fix what I believe to …
> Better inside-horizontal dimensions

- librecad/src/Info.plist.app
- librecad/src/main/lc_application.cpp
- librecad/src/main/lc_application.h
- librecad/src/main/main.cpp
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/main/qc_applicationwindow.h
- librecad/src/src.pro
- Adds required information for open with to Info.plist
- Uses a QApplication subclass to catch the file open events prior to the event filter being in place
- Creates an Event filter in the main window for QApplication for fileopen events that are received
> fixes #877

- librecad/src/lib/engine/rs_dimaligned.cpp
- librecad/src/lib/engine/rs_dimlinear.cpp
This was reported by dellus on the forum:
http://forum.librecad.org/Inside-horizontal-dimensions-tp5715827p5715872.html
I'm not *certain* what the correct behavior should be, but this seems
right to me (scaling with General Scale).
Standard general scale of 1:
After setting general scale to 2:
> fixed length extension lines should scale according to the General Scale

- librecad/src/actions/lc_actionfileexportmakercam.cpp
- librecad/src/lib/generators/lc_makercamsvg.cpp
- librecad/src/lib/generators/lc_makercamsvg.h
- librecad/src/ui/forms/qg_dlgoptionsmakercam.cpp
- librecad/src/ui/forms/qg_dlgoptionsmakercam.h
- librecad/src/ui/forms/qg_dlgoptionsmakercam.ui
- librecad/src/ui/lc_actionfactory.cpp
- renamed to Export as CAM/plain SVG;
- MakerCAM option description, which originally was implemented as QLabel, replaced with ToolTips - to make it more similar to other UI/save space in dialog;
- all options by default is the same, as was before;
- added option to set line width (it was hardcoded to 1mm, so default value is the same)
- added export of image and corresponding option to dialog (absolute path used)
- added baking of lines of all supported types (dot, dash, dashdot, etc) to used it in CAM's
related forum thread - http://forum.librecad.org/SVG-Import-Export-td5715881.html
> SVG export changes/updates

- librecad/src/ui/forms/qg_commandwidget.cpp
- librecad/src/ui/generic/colorwizard.cpp
- librecad/src/ui/generic/widgetcreator.cpp
The new Qt removed some implicit inclusions of headers. To avoid build
errors, add explicit includes of those we use in the sources.
> fix build with Qt 5.11

- librecad/src/lib/engine/rs_undocycle.cpp
Fix simple copy/paste/undo by removing deleted entities from the undo cycle.
This probably introduces glitches in complicated undo chains,
but this is preferable to a segfault.
> Fix copy/paste/undo

- librecad/src/ui/forms/qg_dlginsert.cpp
In the 'Insert' properties dialog the Row Spacing field value is actually displaying and saving column spacing, and the Column Spacing field value is actually displaying and saving row spacing. Fixing that.
> Fix: RowSpacing and ColSpacing values were swapped in Insert dialog

- librecad/src/lib/modification/rs_modification.cpp
This is reopening of #1029 pull request with check for user inputs 0 as factor value. Substituting 0 with 1.0 for preventing empty blocks inserts.
> Fix: Factor value was ignored on block import

- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/ui/qg_actionhandler.cpp
When all MDI windows are closed there are a bunch of document-dependent actions available through **File** menu (which obviously should be disabled, but they are not). Most of those actions don't cause any segfaults. But two of them do:
1. **File->Import->Block**
2. **File->Export->Export as CAM/plain SVG**
The first is pretty easy to fix by checking for MDI window in `QC_ApplicationWindow::slotImportBlock()` as most of the similar code does.
The second is trickier and is rooted down to `QC_ActionHandler::setCurrentAction()`. Although inside that method there is a check for if _view_ is NULL or if _document_ is NULL, neither _view_ nor _document_ is set to NULL after closing document window.
Fix for the second segfault cause probably should be thoroughly tested for any side effects, …
> Fixed 2 segfaults causes

- librecad/src/lib/engine/rs_units.cpp
Fix a minor misspelling in the comments that was
(probably) picked up by copy-and-paste and repeated.
> Fix a repeated typo in comments

- librecad/src/lib/modification/rs_modification.cpp
There is an issue for me, when importing a block from file or library it is almost always inserted to layer 0 no matter what layer is selected. For example, in LibreCAD 2.1.3 that wasn't the case. In this pull request I try to fix that issue. But there is a block of code which tries to 'select the same layer in graphic as in source' (I just commented it out). I don't really understand why it is needed. Please feel free to reject this pull request if it breaks anything vital.
> Possible fix: import block to active layer

- librecad/src/lib/modification/rs_modification.cpp
I believe this fixes that old issue. Tested with different combinations of blocks, including different layers, different colors, line types, widths, blocks inside blocks to several insertion levels. Encountered no side effects or differences in exploded results.
> Exploded entities issues fix (#819)

- librecad/src/actions/rs_actionprintpreview.cpp
- librecad/src/lib/engine/rs_graphic.cpp
- librecad/src/lib/engine/rs_graphic.h
- librecad/src/main/qc_applicationwindow.cpp
This pull request attempts to fix #592, #605, #705.
Also it tries to make paper always fully visible when switching to preview view thus making it more consistent with any drawings.
All drawings have paper size A3, landscape.
1. Paper scale is not set, drawn a rectangle which is less than paper.
2. Paper scale is not set, drawn a rectangle which is bigger than paper.
3. Paper scale is 1:10 saved to drawing, drawn a rectangle which is less than paper.
4. Paper scale is 1:10 saved to drawing, drawn a rectangle which is bigger than paper.
5. Paper scale is 10:1 saved to drawing, drawn a rectangle which is less than paper.
6. Paper scale is 10:1 saved to drawing, drawn a rectangle which is bigger than paper.
All drawings display as expected, paper always fits preview window. With drawings …
> Respect paper scale with 'fixed' checked. Issues #592, #605, #705.

- librecad/src/main/qc_applicationwindow.cpp
The segfault appeared as side effect of #1032. During my search for causes I found out that after steps described in #1048, when the 'Closing Drawing' dialog was canceled, the MDI subwindow was not activated. Therefore, **actionHandler**'s **view** and **document** wasn't properly set (they were NULL) causing the segfault. I found a piece of code probably fixing some similar issue:
https://github.com/LibreCAD/LibreCAD/blob/8604f171ee380f294102da6154adf77ab754d403/librecad/src/main/qc_dialogfactory.cpp#L126-L128
and added it to QC_ApplicationWindow::queryExit(). Segfault has gone.
> Fixed segfault cause of #1048

- librecad/src/ui/qg_librarywidget.cpp
- librecad/src/ui/qg_librarywidget.h
This PR allows user to use newly added parts library items in Library Browser without restarting LibreCAD.
Two buttons were added:
* Refresh
* Rebuild
The 'Refresh' button allows user to see newly created directories and items in parts library. But it has a limitation -- it cannot remove deleted directories from the tree. This is where 'Rebuild' button is useful.
The 'Rebuild' button completely recreates directory structure. But it too has a limitation. After hitting this button the user loses his current position within expanded tree and gets an unexpanded tree.
So, both buttons have their usage scenarios and useful in one or another situations.
> Buttons to refresh Library Browser contents

- librecad/src/lib/engine/rs_settings.cpp
As mentioned here: https://github.com/LibreCAD/LibreCAD/issues/859#issuecomment-471971179. There are also other things in LibreCAD that would benefit from this change. For example, clicking OK button in Application Preferences dialog was making it hung for 3-4 seconds on my computer before actual closing. After this change it closes instantly.
> Skip re-saving already saved settings values

- scripts/postprocess-windows/nsis-5.4.nsi
As @foone complains on twitter often enough, this should not require
agreement for use since GPL is not an EULA.
The definitions are inspired from the similar NSIS setup file from VLC.
> setup: don't require the user to agree to GPL to complete setup.

- librecad/src/lib/modification/rs_modification.cpp
- librecad/src/lib/modification/rs_modification.h
- librecad/src/ui/forms/qg_dlgattributes.cpp
- librecad/src/ui/forms/qg_dlgattributes.ui
This tries to extend #762, fixes #1080, makes cautious approach for #755. User now has options to choose if he/she wants to apply attributes recursively to INSERTs.
UPDATED, see https://github.com/LibreCAD/LibreCAD/pull/1088#issuecomment-486094751
<del>Unfortunately, I tried but failed to implement Undo for modified recursively Block entities. Anyway, I think this is a little bit better for the moment than bare #762.</del>
> Fix for #1080 and #755

- librecad/src/actions/rs_actionprintpreview.cpp
If Shift key is pressed the paper moves only horizontally.
If Control key is pressed the paper moves only vertically.
> Print Preview: Limit paper movement.

- plugins/divide/divide.cpp
- plugins/divide/dividedlg.cpp
- plugins/divide/dividedlg.h
Prior to this commit, the dialog for the Divide plugin contained
numerous explicit specifications of the number of pixels to leave for
various items. As a result, the dialog was unreadable to the point of
being nearly unusable on displays with pixel densities outside the
originally contemplated design range.
This change removes all explicit geometry specifications
in favor of using QLayout objects to construct the dialog and place all of
the widgets. This way, the dialog can flexibly adapt to whatever display
and fonts are being used.
As a small side cleanup, this commit resolved one confusion between the
size and quantity fields, and made the labeling of these primary parameters
clearer. Also, it removed the explicit calculation of where the error message
box would be placed on screen, …
> Make layout of the Divide plugin independent of pixel density

- librecad/src/actions/rs_actiondefault.cpp
- librecad/src/actions/rs_actiondefault.h
- librecad/src/actions/rs_actiondrawline.cpp
- librecad/src/actions/rs_actiondrawline.h
- librecad/src/actions/rs_actionmodifymirror.cpp
- librecad/src/actions/rs_actionmodifymove.cpp
- librecad/src/actions/rs_actionmodifymove.h
- librecad/src/lib/actions/rs_snapper.cpp
- librecad/src/lib/actions/rs_snapper.h
- librecad/src/lib/engine/rs_entitycontainer.cpp
- librecad/src/lib/engine/rs_entitycontainer.h
- librecad/src/lib/engine/rs_line.cpp
- librecad/src/lib/engine/rs_line.h
The LibreCAD has a great feature: when drawing a line by a mouse and holding the "shift" key during placing the line endpoint, one can move the cursor only along certain angles (0°, 15°, 30°, 45°, etc.).
This code modification enables this feature also for moving and copying entities. I. e. when the reference point is selected and the entity is moved, by pressing the "Shift" key one can move the reference point (and the entity) only along the certain angles (0°, 15°, 30°, 45°, etc.) measured from the original reference point position.
> Angle constraint with pressed "shift" key also for moving and copying entities

- librecad/src/lib/engine/rs_graphic.cpp
Hard coded empty field between a drawing and page edges is not needed anymore.
To this purpose a user has to use page margins.
> Fit to whole page.

- librecad/res/icons/icons.qrc
- librecad/res/icons/scaleLineWidth.svg
- librecad/src/actions/rs_actionprintpreview.cpp
- librecad/src/actions/rs_actionprintpreview.h
- librecad/src/lib/gui/rs_graphicview.cpp
- librecad/src/lib/gui/rs_graphicview.h
- librecad/src/main/qc_applicationwindow.cpp
- librecad/src/ui/forms/qg_printpreviewoptions.cpp
- librecad/src/ui/forms/qg_printpreviewoptions.h
- librecad/src/ui/forms/qg_printpreviewoptions.ui
By default pen width is not scaled on print and print preview.
This is the standard (AutoCAD like) behavior.
But some times it may be useful to enable the pen width scaling when
printing A1 drawing on A4 paper in testing purposes, for example.
> Print Preview: Line width scaling

- librecad/src/main/main.cpp
Wayland uses the .desktop file to find the app name and icon. Without it being specified the correct icon is not shown.
Tested on Gnome/Wayland.
References:
- https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon
- https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop
> Fix missing app name and icon on Wayland

- librecad/src/actions/rs_actionmodifytrim.cpp
- librecad/src/actions/rs_actionmodifytrim.h
Fixes #974, specifically the first comment with regard to the trim tool (https://github.com/LibreCAD/LibreCAD/issues/974#issue-314384893). Demo below:
I plan to submit a separate PR for the second comment (regarding orthogonal lines) shortly.
> Unhighlight limiting entity after exiting Trim tool

- librecad/src/ui/qg_actionhandler.cpp
Fixes #1040. The "Move to Bottom" command now works when there is an existing selection. Demo below:
> Fix for 'move to bottom' command with existing selection

- librecad/src/actions/rs_actionpolylineequidistant.cpp
Fixes #682. Equidistant polylines are now created in the currently selected layer.
> Create equidistant polylines in currently selected layer

- librecad/src/actions/rs_actiondrawimage.cpp
Added auto-zoom after redrawing the inserted image in "RS_ActionDrawImage::trigger"  function. 
Due to "Can't import SVG???" #1162  - This does not completly resolve  author's request  (according to the project wiki SVG cannot be open), but now there should be no confusion ("where is my image?!")  after insertion.
> added auto-zoom after inserting an image

- librecad/src/lib/engine/rs.h
- librecad/src/lib/engine/rs_units.cpp
- librecad/src/lib/printing/lc_printing.cpp
Removed:
- envelope size: C5E, Comm10E, DLE, ISO "C" Series
- small sizes (smaller than A4, B4 and Letter), unusual sizes (Executive, Folio)
- Arch E1, E2, E3 (unsupported)
Added ANSI sizes
- Ansi_A, Ansi_B, Ansi_C, Ansi_D, Ansi_E
Reordered page size
- A series, 0 - 4
- B series, 0 - 4
- Letter
- Legal
- Ledger
- ANSI A - E
- Arch A - E
Corrected precision of US page sizes - added millimeter decimal place 
- Letter
- Legal
- Ledger
Files changed:
lib/engine/rs.h
lib/engine/rs_units.cpp
lib/printing/lc_printing.cpp
Test #1
- Draw rectangle equal to paper size
- Open Print Preview
- Click Fit to Page, note "Scale"
- Set Paper Format (Drawing Prefs) to match rectangle
- Click Fit to Page and note "Scale". (Should be "1:1" and rectangle is at perimeter of page.)
- Close Print Preview
Test #2 …
> Page sizes

- librecad/src/main/qc_applicationwindow.cpp
There is possibility of null pointer dereference
in some systems while opening or creating a file
Detected with wayland-based tiling WM (sway)
Signed-off-by: Vyacheslav Tyrtov <v.tyrtov@gmail.com>
> fix null pointer dereference in main window

- librecad/src/ui/forms/qg_moverotateoptions.cpp
Prior to this change, because of an inconsistency between
librecad/src/ui/forms/qg_moverotateoptions.cpp using "MoveRotate" for
the name of the settings holding the angle but
librecad/src/ui/forms/qg_lg_moverotate.cpp using "MoveRotateAngle", the
previously used value of this angle would not show up in the next
invocation of the MoveRotate dialog; rather, it would always be 30 degrees.
This commit fixes this unhelpful behavior by conforming both files
to use "MoveRotateAngle" as the name of the setting. Now the previously
used value of the angle does show up in the next invocation of the dialog.
> Fix persistence of the angle in a MoveRotate operation

- librecad/src/lib/engine/rs.h
- librecad/src/lib/engine/rs_units.cpp
- librecad/src/lib/printing/lc_printing.cpp
Removed ISO "B" sizes, fixed issue with ANSI B / Ledger / Tabloid (and ANSI A / Letter)
ANSI A Print preview (ANSI B similar):
ANSI A pdf export:
[ANSI-A_Export.pdf](https://github.com/LibreCAD/LibreCAD/files/4775545/ANSI-A_Export.pdf)
ANSI B pdf export:
[ANSI-B_Export.pdf](https://github.com/LibreCAD/LibreCAD/files/4775546/ANSI-B_Export.pdf)
Files changed:
rs.h
rs_units.cpp
lc_printing.cpp
Refer #724, #1247
> Fix b sizes

- libraries/libdxfrw/src/drw_entities.cpp
Splines were parsed incorrectly when weight == 0 - fixed
weight type was changed to int to print it correctly during debug
(there is no DRW_dbg::print(unsigned char) and std::string was used)
Signed-off-by: Vyacheslav Tyrtov <v.tyrtov@gmail.com>
> libdxfrw: fix spline parsing

- plugins/list/list.cpp
Currently the Height value of a point imported via the asciifile plugin only could be stored as a text near the point.
This commit would allow the List Entities plugin to retrieve the point of insertion of any text plus the text contents.
That would make possible to, via an apropiate script, correlate a point with its text height value.
HTH
Pere
> List entities plugin: Add text insertion point and text content to its output

- librecad/src/lib/engine/rs_ellipse.cpp
With boost 1.76, we see:
```
lib/engine/rs_ellipse.cpp:70:15: error: 'tuple' in namespace 'boost::math' does not name a template type
70 |  boost::math::tuple<double, double, double> operator()(double const& z) const {
|               ^~~~~
```
Fix this by including the proper boost header.
> add boost tuple include to fix build

- libraries/libdxfrw/src/drw_entities.cpp
This fixes issue #1468
This patch is based on other similar code in the same function, e.g.
```c++
case 73:
if (arc) arc->isccw = reader->getInt32();
else if (pline) pline->flags = reader->getInt32();
break;
```
The end result is that if code 93 comes before the code 92 which would initialize the `loop` pointer, the code 93 is ignored.
> Added NULL check for DXF hatch code 93, Fixing issue #1468

- libraries/libdxfrw/src/drw_entities.cpp
This fixes issue #1474, where any use of the vertex list would cause a crash.
> Correct bounds check in DRW_LWPolyline, fixing issue #1474

- librecad/src/lib/engine/rs_ellipse.cpp
- librecad/src/lib/engine/rs_system.cpp
Found via `codespell -q 3 -S *.ts,./libraries,*.dxf,*.lff,*.desktop -L ans,atleast,ba,bload,ded,inout,lightyear,recources,trun`
> FIx various source comment typos

- librecad/src/ui/forms/qg_activelayername.ui
- librecad/src/ui/forms/qg_coordinatewidget.ui
- librecad/src/ui/forms/qg_mousewidget.ui
- librecad/src/ui/forms/qg_selectionwidget.ui
Since all of these widgets shrink to fit their content anyway, there is
really no downside to larger maximum sizes, and they prevent the text
content of the widgets from being clipped on hidpi displays.
> fix: increase maximum sizes of statusbar widgets to accommodate hidpi

- librecad/src/lib/engine/lc_splinepoints.cpp
* Solved issue #1395
The code talks about _splines_, but bears the equation of a _quadratic Bézier curve_.
Also, there is an analytic equation (which is generic) to compute the n-th degree Bézier curve, 
but the author of the code uses a very different approach (which is not compatible with the 
aforementioned analytic equation).
> snap on middle fails for last point on spline, fixes #1395

- librecad/src/ui/forms/qg_dlgtext.ui
The tab order of elements in the text dialog box was a bit counterintuitive, so I've added a tab order.  Hopefully it's logical:
> Update tab order qg_dlgtext.ui

- librecad/src/ui/forms/qg_dlgpolyline.cpp
* Solved issue #1496
<hr>
A very amusing fact is that you might think that the problem arises from the function that deals with setting the line type, but no, not at all. It comes from the function that deals with closing the polyline.
This change fixes the mentioned issue; though I am unaware of its implications elsewhere.
But, as it only deals with the extrinsic properties of lines, and _not_ their physical shape, it shouldn't pose any problem.
> fillets caused spurious lines, fixes #1496

- librecad/src/ui/qg_blockwidget.cpp
- librecad/src/ui/qg_layerwidget.cpp
Before the change, toggling layer visibility (or in essence updating
contents of layerwidget) caused it to scroll to the active layer. Such
behaviour is problematic especially for drawings with large number of
layers.
Fix is simple - don't set active layer during layerwidget update.
> don't scroll layer widget after toggling layer visibility, fixes #1515

- librecad/src/lib/engine/rs_blocklist.cpp
- librecad/src/lib/engine/rs_entitycontainer.cpp
Block list fix:
When block A that is nested within block B is renamed, then rename
also all inserts of block A withing block B in the blocklist.
Entity container fix:
RS_Insert is a subclass of RS_EntityContainer. Inserts within
inserts (in entity tree of a graphic) should be renamed as well.
Fixes issue #1527
> renaming of nested blocks, fixes #1527

- librecad/src/ui/lc_widgetfactory.cpp
Solution:
Tooltips are added by insertion of "setToolTip()" calls within the
librecad/src/ui/lc_widgetfactory.cpp source file, function
LC_WidgetFactory::createCategoriesToolbar().
> no tooltips shown for widgets on the 'Categories' toolbar, fixes #1519

- scripts/postprocess-windows/nsis-4.8.nsi
- scripts/postprocess-windows/nsis-5.0.nsi
- scripts/postprocess-windows/nsis-5.1.nsi
- scripts/postprocess-windows/nsis-5.2.nsi
- scripts/postprocess-windows/nsis-5.3.nsi
- scripts/postprocess-windows/nsis-5.4.nsi
Possibly closes #1600
I am not on a Windows machine so this PR is untested, but I don't see a reason why it shouldn't work. The added instruction simply skips over the command to navigate to the website. If it's required I can try spinning up a VM with Windows to really test it out, or maybe someone else can do it on their PC?
> Add IfSilent jump instruction to skip browser launch after install

- tools/ttf2lff/freetype.pri
```
clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o ../../LibreCAD.app/Contents/MacOS/ttf2lff generated/obj/main.o   -L/usr/local/lib -lfreetype
Undefined symbols for architecture x86_64:
"_inflate", referenced from:
_FT_Gzip_Uncompress in libfreetype.a(ftgzip.o)
_ft_gzip_file_fill_output in libfreetype.a(ftgzip.o)
"_inflateEnd", referenced from:
_FT_Stream_OpenGzip in libfreetype.a(ftgzip.o)
_ft_gzip_stream_close in libfreetype.a(ftgzip.o)
_FT_Gzip_Uncompress in libfreetype.a(ftgzip.o)
"_inflateInit2_", referenced from:
_FT_Stream_OpenGzip in libfreetype.a(ftgzip.o)
_FT_Gzip_Uncompress in …
```
> Fix linker error when linking freetype w/ ttf2lff

- librecad/src/lib/math/rs_math.cpp
- librecad/src/lib/math/rs_math.h
Implementation for https://sourceforge.net/p/librecad/feature-requests/41/
Adds the ability to parse commands containing unit symbols.
The idea behind this implementation was to add a few new measurement specification parsing options based on the number of feature requests I found, and to make it possible (and not too difficult) to add further parsing options in the future as needed.
Accepted command patterns (Negative symbol "-" may precede measurement string):
1) DMS with required degree and optional minutes/seconds:
- Degrees: degree[s] | deg | [Dd] | ° <required, else not matched>
- Minutes: minute[s] | min | [Mm] | ' <optional>
- Seconds: second[s] | sec | [Ss] | " <optional>
2) Metric string containing meters, centimeters, millimeters:
- Meters: meter[s] | m <optional>
- …
> Handle fractional imperial dimensions

- librecad/src/lib/engine/rs_units.cpp
This is PR #1390 by [Nick Deubert] (https://github.com/ndeubert)
Hide zero foot in the architecture format for zero foot.
> Hide zero foot

- librecad/src/lib/math/rs_math.cpp
* Solved issue #1386
<hr>
It fails because the two _parallel_ lines are always registered as _intersecting_ lines. The actual problem lies in the `RS_Math::linearSolver()` function that is called by the `LC_Quadratic::getIntersection()` function.
The tolerance set was too low (`TOLERANCE2 = 1.0E-20`), and such a tolerance (by its definition) is only meant to be used when dealing with decimal multiplication. I've set it to the basic `TOLERANCE = 1.0E-10`.
It seems to be working all fine now.
<hr>
Video link :  [https://youtu.be/ldPNDQmRnqA](https://youtu.be/ldPNDQmRnqA)
> tangent 3 circle sometimes fails with parallels, fixes #1386

- libraries/libdxfrw/src/libdxfrw.cpp
- libraries/libdxfrw/src/libdxfrw.h
Dimstyle should use the Text Style handle ID not the name.
http://docs.autodesk.com/ACD/2011/ENU/filesDXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a53.htm
> Change DXF Export to use ext Style handle ID for 340 Dimstyle field.

- librecad/src/actions/lc_actionlayersexport.cpp
- librecad/src/actions/rs_actiondefault.cpp
- librecad/src/actions/rs_actiondefault.h
- librecad/src/lib/actions/rs_snapper.cpp
- librecad/src/ui/qg_graphicview.cpp
Issue #1640 : limit the effect size by screen units
Fixed a crash due to the glowing effect
ToDo: separate glowing effects from the geometry layer. 
Also fixed issue #1637, a building issue due to qt-5.15 support changes
> Fixes for glowing effect on mouse hovering

- librecad/src/actions/rs_actiondefault.cpp
- librecad/src/ui/forms/qg_dlgoptionsgeneral.cpp
- librecad/src/ui/forms/qg_dlgoptionsgeneral.ui
Add an application option to enable the glowing effects for mouse-over events on an entity.
The option is disabled by default.
> Issue #1645: user option for mouse-over effects

- librecad/src/lib/engine/rs_entitycontainer.cpp
- librecad/src/lib/engine/rs_entitycontainer.h
- librecad/src/lib/engine/rs_hatch.cpp
- librecad/src/lib/engine/rs_line.cpp
- librecad/src/ui/forms/qg_dlgoptionsgeneral.ui
Find the hatch area using topology of the boundary loops.
1. support topologies like islands in lakes or lakes on islands;
2. The boundary loops are allowed to touch each other;
3. Shared boundary edges among loops not supported;
4. Boundary edges should have simple connectivity: each end point of an edge should be shared by exact two consecutive edges. 3 or more edges connected to a single point is not supported.
A test case dxf:
[hatch1.zip](https://github.com/LibreCAD/LibreCAD/files/12061078/hatch1.zip)
> Issue #1572 : add topology sorting for hatch loops

- librecad/src/actions/rs_actiondefault.cpp
- librecad/src/lib/engine/lc_splinepoints.cpp
- librecad/src/lib/engine/rs.h
- librecad/src/lib/engine/rs_arc.cpp
- librecad/src/lib/engine/rs_circle.cpp
- librecad/src/lib/engine/rs_ellipse.cpp
- librecad/src/lib/engine/rs_line.cpp
- librecad/src/lib/gui/rs_linetypepattern.cpp
- librecad/src/lib/gui/rs_linetypepattern.h
- librecad/src/lib/gui/rs_painterqt.cpp
- librecad/src/lib/gui/rs_painterqt.h
To avoid dash pattern and anti-aliasing issues (#778, #1657, #1658), use Qt native methods to handle line dash patterns.
Modified draw() methods for: RS_Line, RS_Arc, RS_Circle, RS_Ellipse.
Since QPainter doesn't support drawing elliptic arc natively, elliptic arcs are drawn as clipped complete ellipses.
This commit is expected to be experimental, and may be reverted in the future due to potential regressions.
> Issue #778 Painter: use Qt native dash pattern

- CHANGELOG.md
- librecad/src/lib/gui/rs_eventhandler.cpp
In using the LibreCAD command line, I find that far and away the most common point that needs to be entered is simply the current point (the origin for relative coordinates). I am aware that "0..0" specifies this, but that is four fairly awkward keystrokes. Hence, I suggest that a single-character shortcut is well worth it. This commit implements "." to mean the current point (i.e. same as "0..0") when coordinates are expected on the command line. The shortcut was chosen because a bare "." has no other meaning, and it could be read "point" anyway, as a convenient mnemonic. Happy to revise in favor of any other single character if desired. Another possibility that came to mind was a bare "@", chose "." mostly because it's easier to type and because of the cute mnemonic.
Note that as …
> feat: Shortcut "." to specify current point coordinates on command line

- librecad/src/lib/engine/lc_looputils.cpp
- librecad/src/lib/engine/lc_looputils.h
- librecad/src/lib/engine/rs_arc.cpp
- librecad/src/lib/engine/rs_ellipse.cpp
- librecad/src/lib/engine/rs_entitycontainer.cpp
- librecad/src/lib/engine/rs_hatch.cpp
- librecad/src/lib/engine/rs_vector.cpp
- librecad/src/lib/engine/rs_vector.h
- librecad/src/src.pro
- librecad/src/ui/forms/qg_dlgarc.cpp
- librecad/src/ui/forms/qg_dlgarc.ui
- librecad/src/ui/forms/qg_dlgellipse.cpp
- librecad/src/ui/forms/qg_dlgellipse.ui
- librecad/src/ui/forms/qg_dlgline.cpp
- librecad/src/ui/forms/qg_dlgline.h
- librecad/src/ui/forms/qg_dlgline.ui
- librecad/src/ui/forms/qg_dlgspline.cpp
- librecad/src/ui/forms/qg_dlgspline.h
- librecad/src/ui/forms/qg_dlgspline.ui
LibreCAD v3 calculates enclosed area within a contour by an approximate algorithm.
In v2, the area is found by line integration along the contour edges. To support complex contours requires some topology analysis of the contour.
This PR allows support for contours with inner contours (_i.e._ islands within a lake, and lakes on an island within another lake, scenarios).
The algorithm has the following assumptions:
1. Contours are closed loops, so each edge has its start/end points connected to other edges; each loop is simply closed with number of edges equals the number of vertices (Shared endpoints), _i.e._ Euler characteristic 0;
2. Full circles/ellipses are accepted as individual closed contours;
3. No self-intersection among contours; _i.e._ no edge crosses another edge;
4. Multiple …
> Issue #1572: fix hatching area calculation

- CHANGELOG.md
- librecad/src/lib/gui/rs_eventhandler.cpp
This commit adds a shortcut of `,` to specify the current point
(relative origin) when coordinates are expected on the command line,
on top of the recently-added `.` shortcut with the same meaning. (This
addition means that all number pads have a key which can be used for
the current point.) In addition, it adds a shortcut of `0` to mean
`0,0` so that there is a parallel one-character way of specifying
the absolute origin.
(As agreed upon in the discussion re PR #1673.)
> feat: Extend one-character coordinate shortcuts

- librecad/src/main/qc_applicationwindow.cpp
Hello,
This is my first PR, so I picked up a simple issue to start with. As described in Issue #1207, after performing certain actions, LibreCAD always reverts to the first window. I tested this on the 2.2 branch, and the issue persists.
Upon inspecting the code, I noticed that even though there is access to parentWindow, the active window always defaults to the first one in the window list. Since parentWindow is used to determine whether the current window is printPreview or a Block, I utilized this variable to set the focus when closing the current window.
I use LibreCAD for woodworking drawings as a hobby, and while I may not have experience with C++ or QT, I was eager to contribute.
> Exiting print preview displays wrong drawing #1207

- librecad/src/lib/filters/rs_filterdxfrw.cpp
Fixes #863.
[Closed splines](https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-curve-closed.html) have the `p` identical control points in the beginning and at the end of the control points list (where `p` is the degree of the spline).
Some DXF-files contains splines that are defined as closed but actually are open (an example is attached) that causes the incorrect rendering by the LibreCAD. We should verify the closure of the spline by checking the conrol points.
[open-circle-spline-defined-as-closed.dxf.zip](https://github.com/LibreCAD/LibreCAD/files/13403914/open-circle-spline-defined-as-closed.dxf.zip)
> Fix loading of splines that falsely defined by closed

- librecad/src/actions/lc_actiondrawparabola4points.cpp
- librecad/src/actions/rs_actiondrawlinetangent2.cpp
- librecad/src/actions/rs_actiondrawlinetangent2.h
- librecad/src/actions/rs_actionselectwindow.cpp
- librecad/src/lib/creation/rs_creation.cpp
- librecad/src/lib/creation/rs_creation.h
- librecad/src/lib/engine/lc_parabola.cpp
- librecad/src/lib/engine/lc_parabola.h
- librecad/src/lib/engine/rs_arc.cpp
- librecad/src/lib/engine/rs_arc.h
- librecad/src/lib/engine/rs_circle.cpp
- librecad/src/lib/engine/rs_circle.h
- librecad/src/lib/engine/rs_ellipse.cpp
- librecad/src/lib/engine/rs_ellipse.h
- librecad/src/lib/engine/rs_entity.h
- librecad/src/lib/engine/rs_line.h
- librecad/src/lib/math/lc_quadratic.cpp
- librecad/src/lib/math/lc_quadratic.h
Our common tangent (C, C) is now extended to find common tangents for any two conic sections (not considering degenerate lines/points, etc.).
The new algorithm is simplified to a generic common tangent finding algorithm:
1, Find the quadratic form of the dual conic sections of the input ones;
2, It's known that dual curves of conic sections are also conic sections;
3, find intersections of dual conic sections;
4, the intersections are the common tangent in line coordinates of input conic sections;
5, new methods are created to find the tangent point, given a conic section and one of its tangent lines in line coordinates.
Dual curve of a conic section:
Given a general conic section with homogeneous coordinates $[a,b,c,d,e,f]$:
$$ax^2+b x y+c y^2+d x + e y + f = 0 $$
The dual curve is: …
> Parabola support common tangent

- librecad/src/actions/lc_actionmodifybreakdivide.cpp
- librecad/src/actions/lc_actionmodifybreakdivide.h
actually, this is improvement for selection of entities within Break/Divide action - now selection is not affected by current snap mode (snapping to intersection and so on)
> more reliable selection of segments for break/divide action

- librecad/src/lib/engine/rs_dimangular.cpp
- librecad/src/lib/engine/rs_dimradial.cpp
* Solved issue #1328
<hr>
<hr>
> dimension ticks missing on radial and angular, fixes #1328

- librecad/src/lib/debug/rs_debug.h
librecad/src/lib/debug/rs_debug.h requires cstdio to be included because of FILE type being used
log of compilation failure:
```bash
clang++ -c -pipe -g -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DDWGSUPPORT -DQC_APPDIR="librecad" -DLC_VERSION="2.2.0.2-5-g3aa2c41c" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include -I../../libraries/libdxfrw/src -I../../libraries/jwwlib/src -Icmd -Ilib/actions -Ilib/creation -Ilib/debug -Ilib/engine -Ilib/fileio -Ilib/filters -Ilib/generators -Ilib/gui -Ilib/information -Ilib/math -Ilib/modification -Ilib/printing -Iactions -Imain -Imain/console_dxf2pdf -Itest -Iplugins -Iui -Iui/forms -Iui/generic -I../res -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtPrintSupport …
```
> fix compilation with clang and llvm's libcxx

- librecad/src/ui/forms/qg_commandwidget.ui
- librecad/src/ui/generic/colorwizard.ui
- librecad/src/ui/lc_layertreemodel.cpp
- librecad/src/ui/lc_layertreewidget.cpp
- librecad/src/ui/lc_penpalettewidget.cpp
- librecad/src/ui/lc_penpalettewidget.ui
- librecad/src/ui/lc_quickinfowidget.cpp
- librecad/src/ui/lc_quickinfowidget.ui
- librecad/src/ui/lc_widgetfactory.cpp
- librecad/src/ui/qg_blockwidget.cpp
- librecad/src/ui/qg_layerwidget.cpp
This pull request addresses #1805   - plus, adds some polishing for other widgets. 
In my environment, it seems that now widgets are located and resizing more nicely, yet probably it will be necessary to get more feedback from  users, I suspect that the overall operations of docking widgets works under QT6 with some subtle differences comparing to QT5.
> Cmd widget height fix and other widgets polishing

- .github/workflows/build-all.yml
Set different splash for `2.2.2_alpha` (actually only for AppImage / Linux).
Edit Windows / Mac OS workflows to apply this too.
> Set Dark splash for 'alpha'

- .github/workflows/build-all.yml
- librecad/src/ui/components/creators/widgetcreator.ui
- librecad/src/ui/dialogs/entity/qg_dlgarc.ui
- librecad/src/ui/dialogs/entity/qg_dlgline.ui
- librecad/src/ui/dialogs/entity/qg_dlgmtext.ui
- librecad/src/ui/dialogs/entity/qg_dlgtext.ui
- librecad/src/ui/dialogs/file/export/qg_dlgoptionsmakercam.ui
- librecad/src/ui/dialogs/main/qg_dlginitial.ui
- librecad/src/ui/dialogs/settings/options_drawing/qg_dlgoptionsdrawing.ui
- librecad/src/ui/dialogs/settings/options_general/qg_dlgoptionsgeneral.ui
- librecad/src/ui/dialogs/settings/options_widget/lc_widgetoptionsdialog.ui
- librecad/src/ui/dock_widgets/pen_wizard/colorwizard.ui
- librecad/src/ui/not_used/customtoolbarcreator.ui
- librecad/src/ui/not_used/customwidgetcreator.ui
1. Cosmetic cleanup in dialogs UI (setting NoStyle and removing spaces for intermediate frame containers)
2. Switch Dark splash label color to white (for Linux `2.2.2_alpha` AppImage only)
> Minor UI cleanup

- librecad/src/ui/not_used/customtoolbarcreator.ui
- librecad/src/ui/not_used/customwidgetcreator.ui
Just missed to set one more "NoStyle" for Custom Toolbar/Widget dialogs in previous pull
> More minor UI cleanup

- librecad/src/lib/gui/lc_graphicviewport.cpp
Currently, printing a drawing not at origin to pdf results in blank white pages. This is because the coordinate assigned during printing is wrong, and is set to 0. This fixes the code typo when assigning coordinate.
> Fix print to pdf issue

- .github/workflows/build-all.yml
- CI/custom-win-ARM64.nsh
PR Description:
* The adoption of Windows on ARM (WoA) devices is steadily increasing, yet many applications are still not available for this platform.
* GitHub Actions now offer native CI runners for Windows on ARM devices (windows-11-arm), enabling automated builds and testing.
* Currently, official LibreCAD application are not provided for Windows ARM64 and thus users/developers were facing difficulties using popular LibreCAD library natively.
* This PR introduces support for building LibreCAD on Windows ARM64, improving accessibility for developers and end users on this emerging platform.
Note: The generated packages are validated with basic functionality on a local windows arm64 device setup. Working fine as expected and natively on windows arm64 device
> CI: Add support for building LibreCAD binaries for windows arm64

- libraries/libdxfrw/src/drw_entities.cpp
The below commit added DRW_Tolerance::parseCode() without actually returning anything from all except the default case. Return `true` in that case.
The compiler correctly complains:
```
src/drw_entities.cpp:1165:1: error: control reaches end of non-void function [-Werror=return-type]
```
Fixes: 944e6340fe5a (Ordinate Dimensions (#2131))
Noted there:
https://github.com/LibreCAD/LibreCAD/commit/944e6340fe5a1e17a4e44d9de25c78131bfb4cb5#r164908446
> drw_entities: add missing return in DRW_Tolerance::parseCode()

- librecad/src/ui/forms/qg_dlgmtext.cpp
- librecad/src/ui/forms/qg_dlgmtext.h
- librecad/src/ui/forms/qg_dlgtext.cpp
avoid invalid fonts in dlgmtext
> Issue #2069: dlgmtext default to unicode fonts

- librecad/src/lib/engine/rs_entitycontainer.cpp
The root cause: in RS_EntityContainer::optimizeContour(), loops are identified by find the next nearest end point from RS_EntityContainer::getNearestEndpoint(), but getNearestEndpoint() only searches within visible entities, while hatch edges may be set to invisible.
The fix: set edges to be visible temporarily for optimizeContour()
> Issue #2308: fixed loop validation
