LibreCAD/LibreCAD

librecad/src/main/qc_applicationwindow.cpp
This is the underlying problem for issue #493.
=> Skip loading multiple plugins with the same file name.

librecad/src/main/qc_applicationwindow.cpp, librecad/src/ui/forms/qg_dlgoptionsgeneral.cpp, librecad/src/ui/forms/qg_dlgoptionsgeneral.h, librecad/src/ui/forms/qg_dlgoptionsgeneral.ui
* added a variety of default colors to each ComboBox
* made the default colors words instead of unexpected hex codes
* implemented QColorDialog
* rearrangement of the dialog window, because the language ComboBox cramps the color section
=> implemented QColorDialog and added more default colors

librecad/src/main/qc_applicationwindow.cpp, librecad/src/ui/forms/qg_dlgoptionsgeneral.cpp, librecad/src/ui/forms/qg_dlgoptionsgeneral.h, librecad/src/ui/forms/qg_dlgoptionsgeneral.ui, librecad/src/ui/qg_layerwidget.cpp
The `.ui` file shows a lot of changes,
but this was mostly an automatic update.
I had to break the grid layout and then reapply it to fix a bug.
I'm guessing Qt has tweaked the grid layout since it was first applied in our program.
=> added layer/block selection color option

librecad/src/lib/actions/rs_snapper.cpp
* Crosshairs vanish around snapPoint
* Cursor vanishers around snapPoint
=> More effective and precise snapper guide lines (crosshairs)

librecad/src/lib/engine/rs_circle.cpp, librecad/src/lib/engine/rs_circle.h, librecad/src/lib/engine/rs_font.cpp, librecad/src/lib/engine/rs_overlaybox.h, librecad/src/lib/engine/rs_point.h, librecad/src/lib/engine/rs_solid.cpp, librecad/src/lib/engine/rs_solid.h, librecad/src/lib/gui/rs_coordinateevent.h, librecad/src/lib/gui/rs_painter.h
Hi.
I ran the source code through latest cppcheck and found few parts where some optimizations are possible.
Project built nicely on Qt 5.5.1 under Debian Jessie.
=> Some minor performance enhancements

.travis.yml
if this works I can merge in the morning when it is complete
=> Testing optional builds

.gitignore, librecad/src/main/qc_applicationwindow.cpp, librecad/src/main/qc_applicationwindow.h, librecad/src/src.pro, librecad/src/ui/generic/actionlist.cpp, librecad/src/ui/generic/actionlist.h, librecad/src/ui/generic/customwidgetcreator.cpp, librecad/src/ui/generic/customwidgetcreator.h, librecad/src/ui/generic/customwidgetcreator.ui, librecad/src/ui/lc_actionfactory.cpp, librecad/src/ui/lc_widgetfactory.cpp, librecad/src/ui/qg_graphicview.cpp, librecad/src/ui/qg_graphicview.h
:four_leaf_clover: Everything lined up for me to offer this on the equinox. :sunglasses:
=> merging: added custom widget creator and double-click menu; issue #631

librecad/src/lib/engine/rs_blocklist.cpp, librecad/src/lib/engine/rs_entitycontainer.cpp, librecad/src/lib/engine/rs_hatch.cpp
fix: moving/pasting hatch bug
Solve the problem with hatch moving/pasting cause hatch disappears.
This is a quick solution.
There are some minor issues to solve: hatch doesn't appear on the same layer as original after moving.
Closes #714
=> Committer: Equoda <Equoda@users.noreply.github.com>

librecad/src/ui/qg_scrollbar.h
As stated in issue #727, using a lot of entities makes LibreCAD slow. I'm trying to figure out what things can get optimized. I already have one commit which makes it noticeably faster.
~~**Please do not merge yet, I'm going to find more optimizations.**~~
=> Improving rendering performance w.r.t. #727

librecad/src/lib/modification/rs_modification.cpp
Some changes in undo logic for pasting procedure.
Minor changes in code of ```rs_modification.cpp```
=> fix: crash on undo after ctrl+c / ctrl + v; #794

librecad/src/ui/qg_colorbox.cpp
This code now allows for selection of last color in the list
for any layer.
Meant to resolve issue #872 .
=> fix for issue #872 -- Allow selection of last color in selection list

librecad/src/lib/filters/rs_filterdxfrw.cpp
update text object with current relative width before writing to file
=> Update rs_filterdxfrw.cpp; Issue #708

librecad/src/actions/rs_actiondefault.cpp, librecad/src/actions/rs_actiondrawellipsecenter3points.cpp, librecad/src/actions/rs_actiondrawlinefree.cpp, librecad/src/actions/rs_actiondrawpolyline.cpp, librecad/src/lib/engine/lc_splinepoints.cpp, librecad/src/lib/engine/rs_arc.cpp, librecad/src/lib/engine/rs_ellipse.cpp, librecad/src/lib/engine/rs_entitycontainer.cpp, librecad/src/lib/engine/rs_mtext.cpp, librecad/src/lib/generators/lc_makercamsvg.cpp, librecad/src/lib/modification/rs_modification.cpp, librecad/src/main/qc_applicationwindow.cpp, librecad/src/ui/qg_actionhandler.cpp, plugins/asciifile/asciifile.cpp, plugins/importshp/importshp.cpp
gcc7 adds fall-through as default check. Pull request fixes most of the errors (not the ones in the included libraries)
=> Fix warnings made by gcc 7

librecad/src/lib/engine/rs_dimension.cpp, librecad/src/lib/engine/rs_entity.cpp, librecad/src/lib/engine/rs_insert.cpp, librecad/src/lib/engine/rs_line.cpp, librecad/src/lib/filters/rs_filterdxf1.cpp, librecad/src/lib/generators/lc_makercamsvg.cpp, librecad/src/lib/modification/rs_modification.cpp
Found via `codespell -q 3 -I ../librecad-whitelist.txt --skip="*.ts"`
=> Misc. typos

librecad/src/lib/engine/rs_block.cpp, librecad/src/lib/engine/rs_block.h, librecad/src/lib/engine/rs_blocklist.cpp, librecad/src/ui/qg_blockwidget.cpp, librecad/src/ui/qg_blockwidget.h
Similar as filter in Layer List widget.
=> Added filter field to Block List widget

librecad/src/lib/engine/rs_block.h, librecad/src/lib/engine/rs_blocklist.cpp, librecad/src/lib/engine/rs_blocklist.h, librecad/src/lib/engine/rs_blocklistlistener.h, librecad/src/lib/engine/rs_layerlist.cpp, librecad/src/lib/engine/rs_layerlist.h, librecad/src/lib/engine/rs_layerlistlistener.h, librecad/src/main/qc_applicationwindow.cpp, librecad/src/main/qc_mdiwindow.cpp, librecad/src/main/qc_mdiwindow.h
Implementation of window modified mechanism (https://doc.qt.io/qt-5/qwidget.html#windowModified-prop)
=> Modification status mark in window title

librecad/src/ui/qg_graphicview.cpp
As a reference for this fix I was using code from `RS_ActionModifyEntity::trigger()` (it is used by Properties dialog when changing layer of an INSERT). I considered this more appropriate for the issue than using code similar to that of the Attributes dialog (`RS_Modification::changeAttributes(RS_AttributesData& data)`), because the latter still has unresolved issues (#755, #1080).
=> Fix for #1065

libraries/libdxfrw/src/drw_interface.h, libraries/libdxfrw/src/drw_objects.cpp, libraries/libdxfrw/src/drw_objects.h, libraries/libdxfrw/src/libdxfrw.cpp, libraries/libdxfrw/src/libdxfrw.h, librecad/res/icons/icons.qrc, librecad/res/icons/multi_pages.svg, librecad/src/actions/rs_actionprintpreview.cpp, librecad/src/actions/rs_actionprintpreview.h, librecad/src/lib/engine/rs_graphic.cpp, librecad/src/lib/engine/rs_graphic.h, librecad/src/lib/filters/rs_filterdxfrw.cpp, librecad/src/lib/filters/rs_filterdxfrw.h, librecad/src/lib/gui/rs_graphicview.cpp, librecad/src/main/console_dxf2pdf/console_dxf2pdf.cpp, librecad/src/main/console_dxf2pdf/pdf_print_loop.cpp, librecad/src/main/console_dxf2pdf/pdf_print_loop.h, librecad/src/main/qc_applicationwindow.cpp, librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp, librecad/src/ui/forms/qg_dlgoptionsdrawing.h, librecad/src/ui/forms/qg_dlgoptionsdrawing.ui, librecad/src/ui/forms/qg_printpreviewoptions.cpp, librecad/src/ui/forms/qg_printpreviewoptions.h, librecad/src/ui/forms/qg_printpreviewoptions.ui
=> Margins and Tiled Printing

librecad/src/lib/engine/rs_image.cpp
fixed this  http://forum.librecad.org/Scaling-imported-image-td5715529.html
=> Bugfix #1102 modfiy image refresh

README.md
The Users Manual has the clearest description `About` LibreCAD and `Getting Started`.  The wiki contains examples and exercises for learning.
=> Reorder Users Documentation

librecad/src/lib/engine/lc_splinepoints.cpp, librecad/src/lib/engine/rs_arc.cpp, librecad/src/lib/engine/rs_ellipse.cpp, librecad/src/lib/engine/rs_image.cpp, librecad/src/lib/engine/rs_line.cpp, librecad/src/lib/gui/rs_graphicview.cpp, librecad/src/main/qc_applicationwindow.cpp
=> Do not highlight selection on Print Preview

librecad/src/ui/forms/qg_dlgoptionsdrawing.ui
Changed decimals from 2 to 4 in fixed extension line legth (due to issue  #1185 "Fixed length dimension extension lines: more digits please")
=> added more digits to extension lines lenth input box

librecad/src/lib/modification/rs_modification.cpp
=> Fix pasting from clipboard to block.

librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
=> Drawing Preferences: Fix custom landscape paper size resetting.

librecad/src/actions/rs_actionblockssave.cpp, librecad/src/lib/engine/rs_blocklist.cpp, librecad/src/lib/engine/rs_blocklist.h
=> Fix saving to file of the block with inserts.

librecad/src/lib/modification/rs_modification.cpp
=> Modifications: calculate borders of new entities

librecad/src/lib/gui/rs_graphicview.cpp
Accordingly to the request: https://github.com/LibreCAD/LibreCAD/pull/1168#issuecomment-600878989
=> Print Preview: Line Scaling respects General Scale.

librecad/src/lib/engine/rs_color.cpp, librecad/src/lib/engine/rs_color.h, librecad/src/lib/gui/rs_graphicview.cpp
Implementing functionality proposed in #1256 
Program compiled and tested as working.
=> Enhance visibility of black lines on dark backgrounds

libraries/libdxfrw/src/libdxfrw.cpp
=> Add missing subclass marker to PLOTSETTINGS.

librecad/src/main/doc_plugin_interface.cpp, librecad/src/main/doc_plugin_interface.h, librecad/src/plugins/document_interface.h, librecad/src/plugins/intern/qc_actiongetent.cpp, librecad/src/plugins/intern/qc_actiongetent.h, librecad/src/plugins/intern/qc_actiongetpoint.cpp, librecad/src/plugins/intern/qc_actiongetpoint.h, librecad/src/plugins/intern/qc_actiongetselect.cpp, librecad/src/plugins/intern/qc_actiongetselect.h
`s/[Mm]esage/[Mm]essage/`  
This change is untested.
=> Fix source typos 

libraries/libdxfrw/src/drw_base.cpp
Without this file you cannot compile ...
=> Add drw_base.cpp

libraries/jwwlib/src/jwwdoc.h
Added bounds checking to CDataMoji in jww parser.
=> Solved issue #1462

librecad/src/main/qc_applicationwindow.cpp
=> update recent files list when file is saved as ..., fixes #1364

librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp
=> rename fixed length unit label in current drawing preferences, fixes #1453

librecad/src/ui/forms/qg_coordinatewidget.cpp
=> mark relative coordinates in status bar, fixes #1452

librecad/src/actions/rs_actiondimangular.h, librecad/src/actions/rs_actiondrawlineangle.h, librecad/src/lib/filters/rs_filtercxf.cpp, librecad/src/lib/filters/rs_filterlff.cpp
Fix some trivial source comment typos
=> Fix source comment typos

desktop/org.librecad.librecad.appdata.xml
- this is required for flathub submission
- this is in no way specific to flathub
(this doesn't close the issue)
=> Issue #1007 - Update appadata to pass validation

librecad/ts/librecad_pt_br.ts, plugins/ts/plugins_pt_br.ts
I have updated some terms in pt-br translation and added others.
=> Update pt-br translation

librecad/res/icons/delete_freehand.svg, librecad/res/icons/icons.qrc, librecad/res/icons/mtext.svg, librecad/res/icons/order.svg, librecad/src/ui/lc_actionfactory.cpp, librecad/src/ui/lc_widgetfactory.cpp, librecad/src/ui/lc_widgetfactory.h
Suggested fix for points raised by [jbergengh](https://github.com/jbergengh) in Issue 1511, plus changes to fix other tools also missing from the Standard Toolbars and Dock Widgits as noted by [pollywinters](https://github.com/pollywinters) in the same issue.
=> added missing tools from standard tool bar, fixes #1511

librecad/src/cmd/rs_commands.cpp, librecad/src/cmd/rs_commands.h
For PR #1331  by GSStnb,
fixed merge conflicts
=> Add command

librecad/src/ui/qg_colorbox.cpp
This fixes the heap corruption introduced in 716bf87315480da7f58c2c24f74d80d1f7636a16, as reported in #1626 .
=> Fixed a heap corruption upon startup.

librecad/src/actions/rs_actiondefault.cpp, librecad/src/actions/rs_actiondefault.h, librecad/src/lib/engine/rs.h, librecad/src/lib/gui/rs_graphicview.cpp, librecad/src/lib/gui/rs_graphicview.h, librecad/src/ui/forms/qg_dlgoptionsdrawing.ui
#1639 is not a regression, but a new feature of customized point shapes.
This PR fixes some minor appearance issue for the point shape/size setting UI
=> Issue #1639: minor UI fixes for Point options

librecad/src/actions/rs_actiondefault.cpp, librecad/src/actions/rs_actiondefault.h, librecad/src/lib/actions/rs_snapper.cpp, librecad/src/lib/gui/rs_graphicview.cpp, librecad/src/ui/qg_graphicview.cpp
For glowing effects on hovering: this PR moves highlighted entities to Layer 3 of the graphicView
=> PR #1486 fixes

librecad/src/cmd/rs_commands.cpp, librecad/src/lib/engine/rs_font.cpp, librecad/src/lib/engine/rs_spline.cpp, librecad/src/lib/engine/rs_system.cpp, librecad/src/lib/filters/rs_filterdxfrw.cpp, librecad/src/main/console_dxf2pdf/pdf_print_loop.cpp, librecad/src/main/qc_applicationwindow.cpp, librecad/src/ui/forms/qg_dlgoptionsdrawing.cpp, plugins/asciifile/asciifile.cpp, plugins/asciifile/asciifile.h, plugins/picfile/picfile.cpp, plugins/sample/sample.h
Fixes Qt deprecated API call:
1, QString::split();
2, QPrinter::setPaperSize();
3, Ascii plugin
=> Qt-5.15 support

librecad/src/actions/rs_actiondrawmtext.cpp, librecad/src/lib/engine/rs_mtext.cpp, librecad/src/lib/engine/rs_mtext.h, librecad/src/ui/forms/qg_dlgmtext.cpp, librecad/src/ui/forms/qg_dlgmtext.h, librecad/src/ui/forms/qg_dlgmtext.ui
Initial support for Right-to-left text direction for MText
=> Mtext: initial support for Right-to-left text

librecad/src/actions/rs_actiondrawhatch.cpp, librecad/src/lib/engine/lc_looputils.cpp, librecad/src/lib/engine/lc_looputils.h, librecad/src/lib/engine/rs_arc.cpp, librecad/src/lib/engine/rs_ellipse.cpp
Issue #1572: new loop extraction algorithm
The loop extraction algorithm:
1. Find an outermost edge;
2. Search from the edge by the counterclockwise direction;
3. If an edge is connected to multiple edges, choose the edge
which requires the smallest left turning angle.
=> Issue #1572: updated loop extraction algorithm

README.md
Added in commit 309500152f538bee75446d11620f545c4186e0dc
=> Update README.md with the support of dxf2svg

common.pri, libraries/muparser/muparser.pro, librecad.pro, librecad/src/src.pro
Small change in project files to enable C++17 compiling on GCC on Linux Mint Victoria. Compiles and runs. Needs testing on other platforms.
=> Adding support for C++17 in project files.

librecad/src/actions/rs_actiondefault.cpp, librecad/src/actions/rs_actiondimleader.cpp, librecad/src/actions/rs_actiondrawline.cpp, librecad/src/actions/rs_actionmodifymirror.cpp, librecad/src/actions/rs_actionmodifymove.cpp, librecad/src/lib/actions/rs_snapper.h
* Moved snap angle to the header file. Everywhere it was 15 degrees
* Add snapping to leaders (:
Closes #1686
=> Support snapping for leaders

scripts/build-windows.bat
=> CI: deploy options

librecad/src/actions/rs_actionprintpreview.cpp
**Current Drawing Preferences** is under **Options** menu, not **Edit**.
=> "Warning:: Paper size less than 10mm" warning text updated

librecad/src/lib/engine/rs_entitycontainer.cpp, librecad/src/ui/lc_widgetfactory.cpp, librecad/src/ui/main/qc_applicationwindow.cpp
1) just a quick fix for crash on opening drawing with hatch (I've found that case during opening files from https://www.sandiego.gov/sites/default/files/ds-3179_dxf.zip)
2) fix for #1842
=> Fix for #1842

librecad/src/actions/drawing/draw/curve/rs_actiondrawarc3p.cpp, librecad/src/actions/drawing/draw/line/lc_actiondrawlinesnake.cpp, librecad/src/actions/drawing/draw/line/rs_actiondrawline.cpp, librecad/src/actions/drawing/draw/line/rs_actiondrawlineparallel.cpp, librecad/src/actions/drawing/selection/rs_actionselect.cpp, librecad/src/lib/gui/rs_eventhandler.cpp, librecad/src/lib/gui/rs_eventhandler.h, librecad/src/lib/gui/rs_graphicview.cpp, librecad/src/lib/gui/rs_graphicview.h, librecad/src/main/doc_plugin_interface.cpp, librecad/src/plugins/intern/qc_actiongetselect.cpp, librecad/src/ui/dock_widgets/library_widget/qg_librarywidget.cpp, librecad/src/ui/main/qc_applicationwindow.cpp, librecad/src/ui/qg_actionhandler.cpp, librecad/src/ui/qg_actionhandler.h, librecad/src/ui/view/qg_graphicview.cpp
Coding style: avoid naked "nw " operator.
=> EventHandler: setCurrentAction() by shared_ptr

librecad/src/ui/main/qc_applicationwindow.cpp
closes #2133
maybe fixes #2138 as well.
=> fix: quiting dialog saves anyways

CMakeLists.txt, librecad/src/lib/engine/document/entities/rs_dimlinear.h, librecad/src/lib/engine/document/entities/rs_ellipse.cpp, librecad/src/lib/engine/document/entities/tests/rs_ellipse_tests.cpp, librecad/src/lib/math/rs_math.cpp, librecad/src/lib/math/tests/rs_math_tests.cpp, librecad/src/main/main.cpp, plugins/CMakeLists.txt
1. Add tests for ellipse algorithms;
2. Some cmake cleanup.
=> Add unit tests for rs_ellipse
